services:
  web:
    build: .
    container_name: clippdf_web
    env_file: .env
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn clippdf.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120
      "
    volumes:
      - static:/app/staticfiles
    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: clippdf_nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static:ro
    restart: unless-stopped

volumes:
  static:
